version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch-in-action-7.17.4
    environment:
      - node.name=node1
      - cluster.name=elasticsearch-in-action
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - node1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch-in-action

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.4
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d
      - ./log:/log
    ports:
      - "5044:5044"
    networks:
      - elasticsearch-in-action
    depends_on:
      - elasticsearch

  beats:
    image: docker.elastic.co/beats/filebeat:7.17.4
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    container_name: kibana-7.17.4
    environment:
      - elasticsearch.url=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elasticsearch-in-action
    depends_on:
      - elasticsearch

volumes:
  node1-data:
    driver: local

networks:
  elasticsearch-in-action:
