version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - node.name=node1
      - cluster.name=elasticsearch-in-action
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - path.repo=${WORKDIR}/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - node1-data:${WORKDIR}/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    volumes:
      - ./config/logstash/pipeline:${WORKDIR}/logstash/pipeline:ro,Z
      - ./my-log:${WORKDIR}/logstash/my-log
    networks:
      - elk-network
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"

  beats:
    user: root
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elk-network
    volumes:
      - ./config/filebeat/filebeat.yml/:${WORKDIR}/filebeat/filebeat.yml:ro
      # - ./config/filebeat/modules.d/:${WORKDIR}/filebeat/modules.d:ro // co the doc log ma ko can modules
      - ./my-log:${WORKDIR}/filebeat/my-log:ro

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    environment:
      - elasticsearch.url=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elk-network
    depends_on:
      - elasticsearch

volumes:
  node1-data:
    driver: local

networks:
  elk-network:
